version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "8080:80"
    volumes:
      # Mount the custom nginx config as the default site config
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # Mount the built static files
      - ./nginx/statics:/usr/share/nginx/html/statics:ro
    depends_on:
      - service1
      - service2

  service1:
    build: ./service1
    container_name: service1
    environment:
      - PORT=5000
    ports:
      - "5000:5000"

  service2:
    build: ./service2
    container_name: service2
    environment:
      - PORT=5001
    ports:
      - "5001:5001"
