version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "8080:80"
    volumes:
      # Mount the custom nginx config as the default site config
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # Mount the built static files
      - ./nginx/statics:/usr/share/nginx/html/statics:ro
    depends_on:
      - accessra_microservice
      

  accessra_microservice:
    build: ./accessra_microservice
    container_name: accessra_microservice
    environment:
      - PORT=4000
    ports:
      - "4000:4000"